version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: nandinichatterjee
      POSTGRES_PASSWORD: postgresql_tutorial
      POSTGRES_DB: events
    ports:
      - "5433:5432"

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://nandinichatterjee:postgresql_tutorial@postgres:5432/events
